### ISSUE TITLE
Coding issues with GME code

### ISSUE THREAD

**Issue by Hallberg-NOAA** [NCAR/MOM6#109]
There are a number of problems with the new GME code in MOM_hor_visc.F90.  I would fix them myself, but I think that this should be done by someone who has the tests and expertise to evaluate the impacts of the changing answers that will result (perhaps @septicscuzzy).

  Specifically:

- The wrong horizontal loop index bounds are used in many of the GME calculations; you can find the right bounds by working backward from the final result and not doing the calculation over any unnecessary points that will not be used subsequently.
- There are an excessive number of halo updates of intermediate variables and single-variable halo updates that should be grouped into vector updates so they work correctly across the tripolar fold.  Halo updates are very expensive and should be used as sparingly as possible. The rest of the MOM_hor_visc code avoids them by using properly extended loop ranges for intermediate calculations and marching inward, and the same should be done with the GME code.
- All 4-point sums need to have parentheses added so they are rotationally invariant, as in
    h_at_q(I,J) = 0.25*((h(i,j) + h(i+1,j+1)) + (h(i+1,j) + h(i,J+1))
- Several variables, including boundary_mask, target_diss_rate_GME, and max_diss_rate, are calculated on tracer (h) points but are being used at corner (q or Bu) points without any appropriate averaging, so this is a horizontal indexing error. This type of error will be automatically flagged when we get the rotational consistency testing working automatically.
- boundary_mask is being used over a larger range than it was calculated for, so there will likely be non-reproducing results across layout
- In the Leith code, beta_h and beta_q are calculated for every layer but are never used.

  I have a marked-up version of MOM_hor_visc.F90 that I would be happy to share with anyone who is working on addressing this issue, but whoever does the PR to address this issue needs to be working with a test case that exercises this code, and this is not the case with the dev/gfdl version of MOM6-examples.

**Comment by Hallberg-NOAA** [comment]
The version of MOM_hor_visc.F90 that I just checked in at https://github.com/Hallberg-NOAA/MOM6/blob/code_units_cleanup/src/parameterizations/lateral/MOM_hor_visc.F90
includes comments marked with '#GME#' that indicate places where I think that there are issues to consider (described in the previous comment) with the new GME code. There are also some similar issues in MOM_lateral_mixing_coeffs.F90 in calc_QG_Leith_viscosity that might also be worth examining, and which I marked in comments with '###'.

  I hope that this is helpful.

**Comment by septicscuzzy** [comment]
Thanks Bob.  We will make these changes as soon as we can.
