### ISSUE TITLE
Changes to MOM_obsolete_params.F90 causes CESM2+MOM6 to break

### ISSUE THREAD

**Issue by gdicker1** [NCAR/MOM6#110]
Commit #: b9844d797d6aaac43434d3976ea324444bcd7c64
@gustavo-marques 
Following directions at: https://github.com/ESCOMP/MOM_interface/wiki/Quick-Start

When trying to run a case on Cheyenne with the CMOM compset and resolution of T62_t061, MOM6 experiences a fatal error when trying to run due to the inclusion of MIN_Z_DIAG_INTERVAL in one of the param files described for the case.

Errors occur when the job is running on the cluster after the `case.submit` command is issued.

**Comment by gustavo-marques** [comment]
Commit [#36](https://github.com/ESCOMP/MOM_interface/pull/36) in MOM_inerface fixes this.

Another way of fixing it without updating MOM_interface is to delete MIN_Z_DIAG_INTERVAL from MOM_input.
