### ISSUE TITLE
MOM log outputs showing up in cesm.log

### ISSUE THREAD

**Issue by alperaltuntas** [NCAR/MOM6#162]
MOM log output, even from the root task, shows up in cesm.log instead of ocn.log. Stdout for MOM6 must be directed to ocn.log.

**Comment by gustavo-marques** [comment]
I noticed that the latest dev/ncar is sending the output to ocn.*, so I guess this can be closed.

**Comment by gustavo-marques** [comment]
Thanks for fixing this @alperaltuntas

**Comment by alperaltuntas** [comment]
I will need to make some changes for the nuopc cap as well. Also, some of the MOM6 log messages are written via FMS subroutine calls. Since we can't make changes within FMS, those messages will still appear in cesm.log until we have a better control of infrastructure interfaces.

**Comment by gustavo-marques** [comment]
Sounds good. Thanks for the clarification.

**Comment by jedwards4b** [comment]
Using MOM dev/ncar_220225 I see a lot of MOM output still going to cesm.log and I also see a lot of
output to logfile.000000.out.  Ideally the contents of logfile should be in ocn.log.
