### ISSUE TITLE
Local variables not used in CorAdCalc

### ISSUE THREAD

**Issue by gustavo-marques** [NCAR/MOM6#217]
The following variables are never used. @alperaltuntas, should we remove them?  
https://github.com/NCAR/MOM6/blob/b1eda273774965d9f673fb03912b145b17da93e1/src/core/MOM_CoriolisAdv.F90#L188-L191

**Comment by marshallward** [comment]
Our current PR to main removes these (along with all other unused variables) so maybe not necessary.

**Comment by gustavo-marques** [comment]
I am resolving the conflicts by merging your current PR to main, and that's why this showed up.

**Comment by marshallward** [comment]
Ah ok no worries then.

**Comment by alperaltuntas** [comment]
This issue appears to have been fixed. Closing...
