### ISSUE TITLE
Attempt to fetch from allocatable variable LABEL when it is not allocated 

### ISSUE THREAD

**Issue by jedwards4b** [NCAR/MOM6#258]
The error occurred on this line when running with DEBUG=TRUE

https://github.com/NCAR/MOM6/blob/dev/ncar/src/framework/MOM_netcdf.F90#L554

tag is dev/ncar_230829b

running SMS_D.ne30pg3_t232.BLT1850_v0c.derecho_intel

**Comment by marshallward** [comment]
Wow, sorry about that, guess it's not a very helpful error message :facepalm:.  I suspect there could be more instances of this sort of error.

**Comment by alperaltuntas** [comment]
See #261
