### ISSUE TITLE
Support RUN_TYPE=hybrid

### ISSUE THREAD

**Issue by gustavo-marques** [NCAR/MOM6#265]
As reported in https://github.com/NCAR/amwg_dev/discussions/459, MOM6 does not read a restart file when `RUN_TYPE=hybrid`.

[Here](https://github.com/NCAR/MOM6/blob/dev/ncar/config_src/drivers/nuopc_cap/mom_cap.F90#L561-L588) is the relevant code. When `RUN_TYPE=hybrid`, `starttype='startup'` instead of `starttype='continue'` and the simulation is treated as "initial". 

For a temporary fix, manually specify the initial condition files (temp, salt, h, u, and v) through `user_nl_mom` during the initial submission.

**Comment by jedwards4b** [comment]
The way this works for cice6 is that the namelist variable ice_ic is set to the hybrid case restart file.
This causes the variable restart, which was set to false based on the startup=initial to be changed to .true. if the ice_ic file namelist variable is set, that happens [here.](https://github.com/ESCOMP/CICE/blob/main/cicecore/cicedyn/general/ice_init.F90#L872)

**Comment by jedwards4b** [comment]
@gustavo-marques Is this method or something similar possible in Mom?

**Comment by gustavo-marques** [comment]
@jedwards4b, thanks for your help! 
After talking to @alperaltuntas it seems our only option is to do something similar, but via [MOM_interface](https://github.com/ESCOMP/MOM_interface).
