### ISSUE TITLE
REMAP_VEL_CONSERVE_KE  breaks dimensional consistency tests

### ISSUE THREAD

**Issue by gustavo-marques** [NCAR/MOM6#300]
@alperaltuntas found that the dimensional consistency tests break when `REMAP_VEL_CONSERVE_KE = True`.
CC'ing @iangrooms

**Comment by iangrooms** [comment]
OK, I will take a look.

**Comment by iangrooms** [comment]
I can't get dev/ncar to pass dimensional consistency even with `REMAP_VEL_CONSERVE_KE = False`, so I can't make progress on this for now.

**Comment by iangrooms** [comment]
I think the lines that break the dimensional consistency tests are [here](https://github.com/NCAR/MOM6/blob/37411fb6d20387799aa7d24e53728cf025953481/src/ALE/MOM_ALE.F90#L1175C1-L1175C69) and [here](https://github.com/NCAR/MOM6/blob/37411fb6d20387799aa7d24e53728cf025953481/src/ALE/MOM_ALE.F90#L1243). The correction is based on the square root of the ratio of two kinetic energies, and to avoid division by 0 I introduced a dimensional constant 1.E-19. This literal constant doesn't scale in the dimensional consistency tests, which causes the results to change and the test to fail. I changed the code to remove the literal constant [here](https://github.com/iangrooms/MOM6/blob/bd94663b550d98717df43d0aae1da14519cdbffb/src/ALE/MOM_ALE.F90#L1157-L1161) and [here](https://github.com/iangrooms/MOM6/blob/bd94663b550d98717df43d0aae1da14519cdbffb/src/ALE/MOM_ALE.F90#L1229-L1233).

Separately, on the same branch I also changed the computation of the diagnostics `ale_u2` and `ale_v2` to make the code clearer. I don't think this change is necessary to fix the dimensional consistency tests.

**Comment by iangrooms** [comment]
This issue was resolved by #308.
