### ISSUE TITLE
MOM_interface PR #190 Broke Dimensional Consistency test 

### ISSUE THREAD

**Issue by alperaltuntas** [NCAR/MOM6#302]
PR [#190](https://github.com/ESCOMP/MOM_interface) Broke Dimensional Consistency test for the T (time) dimension. All other dimensions are still passing.

**Comment by alperaltuntas** [comment]
A bit more info: The culprit appears to be FULL_DEPTH_KHTR_MIN. Setting it to False fixes the failing dimensional consistency test T. Looking at the checksums of a scaled run with `FULL_DEPTH_KHTR_MIN=True`, the first diff appears in MOM_diabatic driver, after KPP, when compared to a non-scaled run with `FULL_DEPTH_KHTR_MIN=True`.

**Comment by iangrooms** [comment]
On [these](https://github.com/NCAR/MOM6/blob/a8cb1d8c9ffe76b67e995fdc680d742e5a84c825/src/tracer/MOM_tracer_hor_diff.F90#L442) [lines](https://github.com/NCAR/MOM6/blob/a8cb1d8c9ffe76b67e995fdc680d742e5a84c825/src/tracer/MOM_tracer_hor_diff.F90#L434) the `CS%Khtr_min` is compared against `Coef_x` and `Coef_y`, but I'm pretty sure that the dimensions of `Coef_x` and `Coef_y` do not match the dimensions of `CS%Khtr_min`. 

Looking just a few lines up
```
Coef_y(i,J,K) = I_numitts * khdt_y(i,J)
Coef_x(I,j,K) = I_numitts * khdt_x(I,j)
```
`I_numitts` is nondimensional while `khdt_{x,y}` are, as the name suggests, a diffusivity times the time step. In light of this, I think the following might fix the dimensional consistency problem:
```
Coef_y(i,J,K) = max(Coef_y(i,J,K), dt * CS%KhTr_min)
Coef_x(I,j,K) = max(Coef_x(I,j,K), dt * CS%KhTr_min)
```
This would change the results substantially. I haven't tested it.
